/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteMapRouteImport } from './routes/site-map'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProRouteImport } from './routes/pro'
import { Route as MultiRouteImport } from './routes/multi'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExpertiseRouteImport } from './routes/expertise'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'

const SiteMapRoute = SiteMapRouteImport.update({
  id: '/site-map',
  path: '/site-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiRoute = MultiRouteImport.update({
  id: '/multi',
  path: '/multi',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseRoute = ExpertiseRouteImport.update({
  id: '/expertise',
  path: '/expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/detection': typeof DetectionRoute
  '/devices': typeof DevicesRoute
  '/expertise': typeof ExpertiseRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/multi': typeof MultiRoute
  '/pro': typeof ProRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/site-map': typeof SiteMapRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/detection': typeof DetectionRoute
  '/devices': typeof DevicesRoute
  '/expertise': typeof ExpertiseRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/multi': typeof MultiRoute
  '/pro': typeof ProRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/site-map': typeof SiteMapRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/detection': typeof DetectionRoute
  '/devices': typeof DevicesRoute
  '/expertise': typeof ExpertiseRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/multi': typeof MultiRoute
  '/pro': typeof ProRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/site-map': typeof SiteMapRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/detection'
    | '/devices'
    | '/expertise'
    | '/history'
    | '/import'
    | '/multi'
    | '/pro'
    | '/settings'
    | '/setup'
    | '/site-map'
    | '/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/detection'
    | '/devices'
    | '/expertise'
    | '/history'
    | '/import'
    | '/multi'
    | '/pro'
    | '/settings'
    | '/setup'
    | '/site-map'
    | '/join/$code'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/detection'
    | '/devices'
    | '/expertise'
    | '/history'
    | '/import'
    | '/multi'
    | '/pro'
    | '/settings'
    | '/setup'
    | '/site-map'
    | '/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DetectionRoute: typeof DetectionRoute
  DevicesRoute: typeof DevicesRoute
  ExpertiseRoute: typeof ExpertiseRoute
  HistoryRoute: typeof HistoryRoute
  ImportRoute: typeof ImportRoute
  MultiRoute: typeof MultiRoute
  ProRoute: typeof ProRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SiteMapRoute: typeof SiteMapRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site-map': {
      id: '/site-map'
      path: '/site-map'
      fullPath: '/site-map'
      preLoaderRoute: typeof SiteMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi': {
      id: '/multi'
      path: '/multi'
      fullPath: '/multi'
      preLoaderRoute: typeof MultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise': {
      id: '/expertise'
      path: '/expertise'
      fullPath: '/expertise'
      preLoaderRoute: typeof ExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DetectionRoute: DetectionRoute,
  DevicesRoute: DevicesRoute,
  ExpertiseRoute: ExpertiseRoute,
  HistoryRoute: HistoryRoute,
  ImportRoute: ImportRoute,
  MultiRoute: MultiRoute,
  ProRoute: ProRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SiteMapRoute: SiteMapRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
